name: AimTree
version: 0.0.2
description: >-
  none
homepage: none
documentation: none
environment:
  sdk: '>=2.2.0 <3.0.0'
dev_dependencies:
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers: '>=1.2.0 <3.0.0'